
import type { Metadata } from "next";
import { Fira_Sans, Oswald } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firaSans = Fira_Sans({
  weight: "400",
  display: "swap",
  subsets: ["latin"],
  variable:"--font-fira-sans"
});

const oswald = Oswald({
  weight: "400",
  display: "swap",
  subsets: ["latin"],
  style:["normal"],
  variable:"--font-oswald"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${firaSans.variable} ${oswald.variable} `} lang="en">
      <body>
        <Header />
        <main className="main">{children}</main>
        <Footer />
        <Toaster richColors position="top-center"/>
      </body>
    </html>
  );
}
